<?php
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request;
use Drupal\node\Entity\Node;

function etazhmodule_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'comment_comment_form') {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $nodeID = explode('/', $_SERVER['REQUEST_URI']);
        $nodeID = $nodeID[5];
        $form['actions'][$action]['#submit'][] = 'etazhmodule_form_submit';
      }
    }
  }
}

function etazhmodule_form_submit(array $form, FormStateInterface $form_state){
  $nodeID = explode('/', $_SERVER['REQUEST_URI']);
  $nodeID = $nodeID[5];
  $node = Node::load($nodeID);
  if (isset($node)) {
    $node->set('field_object_expertise', 'да');
    $node->save();
    drupal_set_message("Экспертиза объекта #".$nodeID." проведена!");
  }
}
